version: "1"

services:
  db:
    container_name: database
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  bot:
    container_name: bot
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/src
    environment:
      POSTGRES_HOST: db
      TZ: "Europe/Moscow"
    depends_on:
      - db
